export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const INCREMENT1 = 'INCREMENT1';
export const DECREMENT1 = 'DECREMENT1';

export const INCREMENT2 = 'INCREMENT2';
export const DECREMENT2 = 'DECREMENT2';

export const ASYNC_INCREMENT = 'ASYNC_INCREMENT';
export const PROMISE_INCREMENT = 'PROMISE_INCREMENT';